"""Add catalogue story linkage and post likes

Revision ID: 045a56e1bc0c
Revises: dbe1e0d69d80
Create Date: 2026-04-14 22:39:12.094837

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '045a56e1bc0c'
down_revision = 'dbe1e0d69d80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_likes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('post_id', sa.String(length=36), nullable=False),
    sa.Column('buyer_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyer_profiles.id'], ),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'buyer_id', name='_post_buyer_like_uc')
    )
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('catalogue_id', sa.String(length=36), nullable=True))
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=300),
               nullable=True)
        batch_op.create_foreign_key(None, 'catalogues', ['catalogue_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('title',
               existing_type=sa.VARCHAR(length=300),
               nullable=False)
        batch_op.drop_column('catalogue_id')

    op.drop_table('post_likes')
    # ### end Alembic commands ###
