"""add social communication and analytics models v2

Revision ID: 47c79a110d25
Revises: be6e08b6c7eb
Create Date: 2026-04-03 22:24:52.158828

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '47c79a110d25'
down_revision = 'be6e08b6c7eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analytics_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.Enum('artist', 'platform', name='analytics_entity_type'), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=True),
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('metrics', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('sentiment_summary', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('platform_revenue_trend',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('total_revenue', sa.Numeric(precision=14, scale=2), nullable=True),
    sa.Column('total_orders', sa.Integer(), nullable=True),
    sa.Column('active_artists', sa.Integer(), nullable=True),
    sa.Column('new_buyers', sa.Integer(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('month')
    )
    op.create_table('artist_revenue_trend',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('artist_id', sa.String(length=36), nullable=False),
    sa.Column('month', sa.String(length=7), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('orders', sa.Integer(), nullable=True),
    sa.Column('catalogue_views', sa.Integer(), nullable=True),
    sa.Column('story_engagement_rate', sa.Float(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artist_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('artist_id', 'month', name='_artist_month_trend_uc')
    )
    op.create_table('follows',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('buyer_id', sa.String(length=36), nullable=False),
    sa.Column('artist_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artist_profiles.id'], ),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyer_profiles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('buyer_id', 'artist_id', name='_buyer_artist_follow_uc')
    )
    op.create_table('posts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('artist_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Enum('story', 'insight', name='post_type'), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('cover_image_url', sa.String(length=500), nullable=True),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artist_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('buyer_id', sa.String(length=36), nullable=False),
    sa.Column('target_type', sa.Enum('product', 'catalogue', name='review_target_type'), nullable=False),
    sa.Column('target_id', sa.String(length=36), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyer_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('broadcasts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('artist_id', sa.String(length=36), nullable=False),
    sa.Column('catalogue_id', sa.String(length=36), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('intent', sa.Enum('launch', 'preorder', 'flash_sale', 'exclusive_reveal', name='broadcast_intent'), nullable=False),
    sa.Column('platforms', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('draft', 'sent', 'failed', name='broadcast_status'), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artist_profiles.id'], ),
    sa.ForeignKeyConstraint(['catalogue_id'], ['catalogues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('broadcasts')
    op.drop_table('reviews')
    op.drop_table('posts')
    op.drop_table('follows')
    op.drop_table('artist_revenue_trend')
    op.drop_table('platform_revenue_trend')
    op.drop_table('analytics_snapshots')
    # ### end Alembic commands ###
