"""add catalogue_id to products

Revision ID: 7609db7c2361
Revises: 045a56e1bc0c
Create Date: 2026-04-15 02:14:12.674698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7609db7c2361'
down_revision = '045a56e1bc0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('catalogue_id', sa.String(length=36), nullable=True))
        batch_op.create_foreign_key(None, 'catalogues', ['catalogue_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('catalogue_id')

    # ### end Alembic commands ###
