"""Add catalogue models

Revision ID: be6e08b6c7eb
Revises: a1b2c3d4e5f6
Create Date: 2026-04-03 21:43:46.055007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be6e08b6c7eb'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=True),
    sa.Column('full_address', sa.Text(), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('pin_code', sa.String(length=20), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payment_methods',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('card_type', sa.String(length=50), nullable=False),
    sa.Column('last_4', sa.String(length=4), nullable=False),
    sa.Column('expiry_month', sa.String(length=2), nullable=False),
    sa.Column('expiry_year', sa.String(length=4), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('catalogues',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('artist_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('narrative', sa.Text(), nullable=True),
    sa.Column('cover_photo_url', sa.String(length=500), nullable=True),
    sa.Column('theme', sa.Enum('warm', 'earth', 'cool', 'dark', name='catalogue_theme_enum'), nullable=False),
    sa.Column('launch_intent', sa.Enum('live', 'preview', 'preorder', name='catalogue_launch_intent_enum'), nullable=False),
    sa.Column('status', sa.Enum('draft', 'live', 'ended', name='catalogue_status_enum'), nullable=False),
    sa.Column('philosophy', sa.Text(), nullable=True),
    sa.Column('artist_note', sa.Text(), nullable=True),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artist_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('catalogue_likes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('catalogue_id', sa.String(length=36), nullable=False),
    sa.Column('buyer_id', sa.String(length=36), nullable=False),
    sa.Column('liked_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyer_profiles.id'], ),
    sa.ForeignKeyConstraint(['catalogue_id'], ['catalogues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('catalogue_id', 'buyer_id', name='uq_catalogue_like')
    )
    op.create_table('catalogue_products',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('catalogue_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['catalogue_id'], ['catalogues.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('catalogue_id', 'product_id', name='uq_catalogue_product')
    )
    op.create_table('catalogue_stats',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('catalogue_id', sa.String(length=36), nullable=False),
    sa.Column('total_views', sa.Integer(), nullable=False),
    sa.Column('total_likes', sa.Integer(), nullable=False),
    sa.Column('total_revenue', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_orders', sa.Integer(), nullable=False),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['catalogue_id'], ['catalogues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('catalogue_id')
    )
    op.create_table('catalogue_views',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('catalogue_id', sa.String(length=36), nullable=False),
    sa.Column('buyer_id', sa.String(length=36), nullable=True),
    sa.Column('viewed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['buyer_profiles.id'], ),
    sa.ForeignKeyConstraint(['catalogue_id'], ['catalogues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('catalogue_views')
    op.drop_table('catalogue_stats')
    op.drop_table('catalogue_products')
    op.drop_table('catalogue_likes')
    op.drop_table('catalogues')
    op.drop_table('payment_methods')
    op.drop_table('addresses')
    # ### end Alembic commands ###
