"""align platform revenue trend model

Revision ID: dbe1e0d69d80
Revises: 47c79a110d25
Create Date: 2026-04-03 22:59:29.369509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbe1e0d69d80'
down_revision = '47c79a110d25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('platform_revenue_trend', schema=None) as batch_op:
        batch_op.add_column(sa.Column('revenue', sa.Numeric(precision=14, scale=2), nullable=True))
        batch_op.add_column(sa.Column('new_signups', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('avg_order_value', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.drop_column('total_revenue')
        batch_op.drop_column('active_artists')
        batch_op.drop_column('new_buyers')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('platform_revenue_trend', schema=None) as batch_op:
        batch_op.add_column(sa.Column('new_buyers', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('active_artists', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('total_revenue', sa.NUMERIC(precision=14, scale=2), autoincrement=False, nullable=True))
        batch_op.drop_column('avg_order_value')
        batch_op.drop_column('new_signups')
        batch_op.drop_column('revenue')

    # ### end Alembic commands ###
